// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKznPtOKbWF6YlaHblzO8Tao-xiBeSvbY',
    appId: '1:20835456405:web:38389ea07172f6e10b129c',
    messagingSenderId: '20835456405',
    projectId: 'rtbts-74160',
    authDomain: 'rtbts-74160.firebaseapp.com',
    storageBucket: 'rtbts-74160.firebasestorage.app',
    measurementId: 'G-M411YNNMLG',
    databaseURL: 'https://rtbts-74160.firebaseio.com', // <-- ADD THIS LINE
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHnNBPs6HUge7mdLplVJosfXA-f0dJMCg',
    appId: '1:20835456405:android:4fee7fba0087bb5b0b129c',
    messagingSenderId: '20835456405',
    projectId: 'rtbts-74160',
    storageBucket: 'rtbts-74160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI52pX7HJf1FSm9SLm8vToUD2OAYAYJZM',
    appId: '1:20835456405:ios:6b4bb1ccec0aa9180b129c',
    messagingSenderId: '20835456405',
    projectId: 'rtbts-74160',
    storageBucket: 'rtbts-74160.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI52pX7HJf1FSm9SLm8vToUD2OAYAYJZM',
    appId: '1:20835456405:ios:6b4bb1ccec0aa9180b129c',
    messagingSenderId: '20835456405',
    projectId: 'rtbts-74160',
    storageBucket: 'rtbts-74160.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKznPtOKbWF6YlaHblzO8Tao-xiBeSvbY',
    appId: '1:20835456405:web:a80ad53520af13c90b129c',
    messagingSenderId: '20835456405',
    projectId: 'rtbts-74160',
    authDomain: 'rtbts-74160.firebaseapp.com',
    storageBucket: 'rtbts-74160.firebasestorage.app',
    measurementId: 'G-JH402Q829G',
  );
}
